### PR TITLE
add functionality to return the list of experiences

### PR DESCRIPTION
**Pull request by david-wagih**
Added small change actually in the method that runs at thr specified route with GET method that returns a list of all the experiences.

### CODE REVIEW

**Review by fissoreg — COMMENTED** [review]
The implementation looks good, but can you please verify why the tests are failing?

**Comment by david-wagih** [comment]
@fissoreg the test fails because they first test to add w new experience first before getting them back so my PR is just related to getting the list back not adding new one and the same for adding new education and skills

**Comment by fissoreg** [comment]
That makes sense, thank you @david-wagih!

I would suggest to wait for #22 to be merged, then you can rebase your changes on top of it so we can have the tests passing. Does that sound good?

You can go ahead with a new issue in the meanwhile :)

**Comment by david-wagih** [comment]
@fissoreg  okay that sounds good 👍

**Comment by david-wagih** [comment]
@fissoreg 
I have fixed some errors and changes in this branch and now it has all the issues I worked on as this is my main branch, 
but there are 2 tests failing depending on those two issues which should be merged (the one for creating new education and the one for returning all education)

**Comment by david-wagih** [comment]
@fissoreg the branch has no conflicts now, so I think we can work on merging it

**Pull request closed without merging**
